[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.10.8"

[[constraint]]
 name = "github.com/stretchr/testify"
 version = "1.1.4"

[[override]]
 name = "github.com/Azure/go-ntlmssp"
 revision = "c92175d540060095c69ced311f76aea56c83ecdb"

[[override]]
 name = "github.com/ChrisTrenkamp/goxpath"
 revision = "c385f95c6022e7756e91beac5f5510872f7dcb7d"

[[override]]
 name = "github.com/agext/levenshtein"
 revision = "5f10fee965225ac1eecdc234c09daf5cd9e7f7b6"

[[override]]
 name = "github.com/antchfx/xpath"
 revision = "58d12fe685d684ed55aab3b988394652025e36dc"

[[override]]
 name = "github.com/antchfx/xquery"
 revision = "dc53b98b528c0c04904394f77c770d28cbc054ec"

[[override]]
 name = "github.com/apparentlymart/go-cidr"
 revision = "2bd8b58cf4275aeb086ade613de226773e29e853"

[[override]]
 name = "github.com/apparentlymart/go-textseg"
 revision = "b836f5c4d331d1945a2fead7188db25432d73b69"

[[override]]
 name = "github.com/armon/go-radix"
 revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"

[[override]]
 name = "github.com/aws/aws-sdk-go"
 revision = "b79a722cb7aba0edd9bd2256361ae2e15e98f8ad"

[[override]]
 name = "github.com/bgentry/go-netrc"
 revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"

[[override]]
 name = "github.com/bgentry/speakeasy"
 revision = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"

[[override]]
 name = "github.com/blang/semver"
 revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"

[[override]]
 name = "github.com/davecgh/go-spew"
 revision = "ecdeabc65495df2dec95d7c4a4c3e021903035e5"

[[override]]
 name = "github.com/dylanmei/iso8601"
 revision = "2075bf119b58e5576c6ed9f867b8f3d17f2e54d4"

[[override]]
 name = "github.com/dylanmei/winrmtest"
 revision = "c2fbb09e6c084fe3ebe95fce0f1cc5297c152026"

[[override]]
 name = "github.com/go-ini/ini"
 revision = "7e7da451323b6766da368f8a1e8ec9a88a16b4a0"

[[override]]
 name = "github.com/golang/protobuf"
 revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"

[[override]]
 name = "github.com/hashicorp/errwrap"
 revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"

[[override]]
 name = "github.com/hashicorp/go-cleanhttp"
 revision = "3573b8b52aa7b37b9358d966a898feb387f62437"

[[override]]
 name = "github.com/hashicorp/go-getter"
 revision = "2f449c791e6af9e532bc1aca36d1d3865b8537f9"

[[override]]
 name = "github.com/hashicorp/go-hclog"
 revision = "ca137eb4b4389c9bc6f1a6d887f056bf16c00510"

[[override]]
 name = "github.com/hashicorp/go-multierror"
 revision = "83588e72410abfbe4df460eeb6f30841ae47d4c4"

[[override]]
 name = "github.com/hashicorp/go-plugin"
 revision = "e2fbc6864d18d3c37b6cde4297ec9fca266d28f1"

[[override]]
 name = "github.com/hashicorp/go-uuid"
 revision = "64130c7a86d732268a38cb04cfbaf0cc987fda98"

[[override]]
 name = "github.com/hashicorp/go-version"
 revision = "fc61389e27c71d120f87031ca8c88a3428f372dd"

[[override]]
 name = "github.com/hashicorp/hcl"
 revision = "23c074d0eceb2b8a5bfdbb271ab780cde70f05a8"

[[override]]
 name = "github.com/hashicorp/hcl2"
 revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"

[[override]]
 name = "github.com/hashicorp/hil"
 revision = "fa9f258a92500514cc8e9c67020487709df92432"

[[override]]
 name = "github.com/hashicorp/yamux"
 revision = "f5742cb6b85602e7fa834e9d5d91a7d7fa850824"

[[override]]
 name = "github.com/jmespath/go-jmespath"
 revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"

[[override]]
 name = "github.com/masterzen/azure-sdk-for-go"
 revision = "ee4f0065d00cd12b542f18f5bc45799e88163b12"

[[override]]
 name = "github.com/masterzen/simplexml"
 revision = "4572e39b1ab9fe03ee513ce6fc7e289e98482190"

[[override]]
 name = "github.com/masterzen/winrm"
 revision = "a2df6b1315e6fd5885eb15c67ed259e85854125f"

[[override]]
 name = "github.com/mattn/go-isatty"
 revision = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c"

[[override]]
 name = "github.com/mitchellh/cli"
 revision = "65fcae5817c8600da98ada9d7edf26dd1a84837b"

[[override]]
 name = "github.com/mitchellh/copystructure"
 revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"

[[override]]
 name = "github.com/mitchellh/go-homedir"
 revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[override]]
 name = "github.com/mitchellh/go-linereader"
 revision = "07bab5fdd9580500aea6ada0e09df4aa28e68abd"

[[override]]
 name = "github.com/mitchellh/go-testing-interface"
 revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"

[[override]]
 name = "github.com/mitchellh/go-wordwrap"
 revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[override]]
 name = "github.com/mitchellh/hashstructure"
 revision = "2bca23e0e452137f789efbc8610126fd8b94f73b"

[[override]]
 name = "github.com/mitchellh/mapstructure"
 revision = "06020f85339e21b2478f756a78e295255ffa4d6a"

[[override]]
 name = "github.com/mitchellh/reflectwalk"
 revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"

[[override]]
 name = "github.com/nu7hatch/gouuid"
 revision = "179d4d0c4d8d407a32af483c2354df1d2c91e6c3"

[[override]]
 name = "github.com/packer-community/winrmcp"
 revision = "e1b7d6e6b1b1a27984270784190f1d06ad91888b"

[[override]]
 name = "github.com/pmezard/go-difflib"
 revision = "792786c7400a136282c1664665ae0a8db921c6c2"

[[override]]
 name = "github.com/posener/complete"
 revision = "dc2bc5a81accba8782bebea28628224643a8286a"

[[override]]
 name = "github.com/satori/go.uuid"
 revision = "5bf94b69c6b68ee1b541973bb8e1144db23a194b"

[[override]]
 name = "github.com/ulikunitz/xz"
 revision = "0c6b41e72360850ca4f98dc341fd999726ea007f"

[[override]]
 name = "github.com/xanzy/ssh-agent"
 revision = "ba9c9e33906f58169366275e3450db66139a31a9"

[[override]]
 name = "github.com/zclconf/go-cty"
 revision = "8bf222d6d03b7b336d013978f3acbfd877da428f"

[[override]]
 name = "golang.org/x/crypto"
 revision = "453249f01cfeb54c3d549ddb75ff152ca243f9d8"

[[override]]
 name = "golang.org/x/net"
 revision = "a337091b0525af65de94df2eb7e98bd9962dcbe2"

[[override]]
 name = "golang.org/x/sys"
 revision = "0b25a408a50076fbbcae6b7ac0ea5fbb0b085e79"

[[override]]
 name = "golang.org/x/text"
 revision = "88f656faf3f37f690df1a32515b479415e1a6769"

[[override]]
 name = "google.golang.org/genproto"
 revision = "11c7f9e547da6db876260ce49ea7536985904c9b"

[[override]]
 name = "google.golang.org/grpc"
 revision = "409fd8e23b1b48140bc8dc73950f762063baa859"
